# Generated by Django 5.0.1 on 2024-09-23 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin_username = 'admin'
    admin_password = 'adminpassword'

    if not User.objects.filter(username=admin_username).exists():
        User.objects.create_superuser(
            username=admin_username, password=admin_password)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_admin_user)
    ]
