# Generated by Django 5.0.1 on 2024-09-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluserprofile',
            name='report_id',
            field=models.CharField(max_length=100),
        ),
    ]
