# Generated by Django 5.0.1 on 2024-09-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_normaluserprofile_report_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=255, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ad_unit_ids', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ad_unit_id', models.IntegerField()),
                ('ad_unit_name', models.CharField(max_length=255)),
                ('impressions', models.IntegerField()),
                ('clicks', models.IntegerField()),
                ('ctr', models.FloatField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.report')),
            ],
        ),
    ]
