# Generated by Django 5.0.1 on 2024-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_report_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cpm_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(default='Processing', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
