# Generated by Django 5.0.1 on 2024-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_report_cpm_rate_report_status_alter_report_report_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='revenue',
            field=models.FloatField(default=0),
        ),
    ]
