# Generated by Django 5.0.1 on 2024-09-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_record_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
