# Generated by Django 5.0.1 on 2024-09-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_report_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='ad_unit_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='clicks',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='impressions',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='record',
            name='revenue',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
