# Generated by Django 5.0.1 on 2024-09-29 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_record_ad_unit_id_alter_record_clicks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='report_id',
        ),
    ]
