# Generated by Django 5.0.1 on 2024-09-29 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_report_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluserprofile',
            name='report_id',
            field=models.IntegerField(null=True),
        ),
    ]
