# Generated by Django 5.0.1 on 2024-09-29 14:52

from django.db import migrations
from django.contrib.auth.hashers import make_password
import os


def update_admin_password(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    admin_username = 'admin'
    new_admin_password = os.getenv("ADMIN_PASSWORD", "adminpassword")
    # Fetch the admin user by username
    try:
        admin_user = User.objects.get(username=admin_username)
        admin_user.password = make_password(
            new_admin_password)  # Hash the new password
        admin_user.save()
    
    except User.DoesNotExist:
        print(f"Admin user with username '{admin_username}' does not exist.")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_normaluserprofile_report_id'),
    ]

    operations = [
    ]
